version: "3.7"
services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: "test"
    command: bundle exec rake
    ports:
      - "3000:3000"
    links:
      - db
    env_file:
       - .env.test
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/buy-for-your-school-test
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
    volumes:
      - .:/srv/app
    tty: true
    stdin_open: true
    networks:
      - test

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - test

networks:
  test:
volumes:
  db-data:
