name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Debug
        run: docker-compose -v
      - name: Build with Docker Compose
        run: docker-compose -f docker-compose.test.yml build
      - name: DEBUG with Docker Compose
        run: docker-compose -f docker-compose.test.yml run --rm test bash -c "ls -la public"
      - name: Test with Docker Compose
        run: docker-compose -f docker-compose.test.yml run --rm test bundle exec rake
      # - name: Set up Docker
      #   run: docker network create test
      # - name: Set up Postgres
      #   run: docker run -d --name pg --network test -e POSTGRES_USER=test -e POSTGRES_HOST_AUTH_METHOD=trust -p 5432:5432 postgres:11
      # - name: Build a new Docker image
      #   run: docker build . --build-arg RAILS_ENV=test -t app:test
      # - name: Run the tests
      #   run: |
      #     docker run --name test-container \
      #       --network test \
      #       -e RAILS_ENV=test \
      #       -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true \
      #       -e DATABASE_URL=postgres://test@pg:5432/app_test \
      #       app:test bundle exec rake
